/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const DocumentFormat = IDL.Variant({
  'doc' : IDL.Null,
  'pdf' : IDL.Null,
  'txt' : IDL.Null,
  'docx' : IDL.Null,
});
export const ExtendedDocumentMetadata = IDL.Record({
  'id' : IDL.Text,
  'fileName' : IDL.Text,
  'associatedStudent' : IDL.Principal,
  'examinationBoard' : IDL.Opt(IDL.Text),
  'blobId' : IDL.Text,
  'uploadDate' : Time,
  'format' : DocumentFormat,
});
export const QuizResult = IDL.Record({
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'grade' : IDL.Text,
  'correctAnswers' : IDL.Nat,
  'timestamp' : IDL.Int,
  'quizId' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const StudentProgress = IDL.Record({
  'studentPrincipal' : IDL.Principal,
  'bestScore' : IDL.Opt(QuizResult),
  'averagePercentage' : IDL.Float64,
  'quizzesTaken' : IDL.Nat,
  'quizHistory' : IDL.Vec(QuizResult),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocumentMetadata' : IDL.Func(
      [IDL.Text],
      [ExtendedDocumentMetadata],
      ['query'],
    ),
  'getStudentDashboard' : IDL.Func([], [StudentProgress], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listStudentDocuments' : IDL.Func(
      [],
      [IDL.Vec(ExtendedDocumentMetadata)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuizResults' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'uploadDocument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, DocumentFormat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const DocumentFormat = IDL.Variant({
    'doc' : IDL.Null,
    'pdf' : IDL.Null,
    'txt' : IDL.Null,
    'docx' : IDL.Null,
  });
  const ExtendedDocumentMetadata = IDL.Record({
    'id' : IDL.Text,
    'fileName' : IDL.Text,
    'associatedStudent' : IDL.Principal,
    'examinationBoard' : IDL.Opt(IDL.Text),
    'blobId' : IDL.Text,
    'uploadDate' : Time,
    'format' : DocumentFormat,
  });
  const QuizResult = IDL.Record({
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'grade' : IDL.Text,
    'correctAnswers' : IDL.Nat,
    'timestamp' : IDL.Int,
    'quizId' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const StudentProgress = IDL.Record({
    'studentPrincipal' : IDL.Principal,
    'bestScore' : IDL.Opt(QuizResult),
    'averagePercentage' : IDL.Float64,
    'quizzesTaken' : IDL.Nat,
    'quizHistory' : IDL.Vec(QuizResult),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocumentMetadata' : IDL.Func(
        [IDL.Text],
        [ExtendedDocumentMetadata],
        ['query'],
      ),
    'getStudentDashboard' : IDL.Func([], [StudentProgress], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listStudentDocuments' : IDL.Func(
        [],
        [IDL.Vec(ExtendedDocumentMetadata)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuizResults' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'uploadDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, DocumentFormat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };